# Generated by Django 3.2.24 on 2024-03-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('tier', models.CharField(choices=[('L', 'Low'), ('M', 'Mid'), ('H', 'High')], default='L', max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('mode_of_contact', models.CharField(choices=[('EM', 'Email'), ('PC', 'Phone'), ('TX', 'Text'), ('LR', 'Letter')], default='EM', max_length=2)),
            ],
        ),
    ]
